import { RoleDefinition, Song, Setlist, GigEvent, StageRider, BandProfile, AudioMixConfig, MidiMapping, EmergencyCueType } from './types';
import { HOTT_SHOTS_SONGS, HOTT_SHOTS_AUGUST_SETLIST } from './data/hottShotsSongs';

export { HOTT_SHOTS_SONGS, HOTT_SHOTS_AUGUST_SETLIST };

export const ROLE_DEFINITIONS: RoleDefinition[] = [
  { id: 'drums', label: 'Drums & Percussion', shortLabel: 'DRUMS', iconName: 'Drum', defaultColor: '#f97316' },
  { id: 'bass', label: 'Bass Guitar', shortLabel: 'BASS', iconName: 'Activity', defaultColor: '#06b6d4' },
  { id: 'lead_guitar', label: 'Lead Guitar', shortLabel: 'LEAD GTR', iconName: 'Zap', defaultColor: '#eab308' },
  { id: 'rhythm_guitar', label: 'Rhythm Guitar', shortLabel: 'RHYTHM GTR', iconName: 'Music', defaultColor: '#84cc16' },
  { id: 'keys', label: 'Keys & Synths', shortLabel: 'KEYS', iconName: 'Layers', defaultColor: '#a855f7' },
  { id: 'lead_vocals', label: 'Lead Vocals', shortLabel: 'LEAD VOX', iconName: 'Mic', defaultColor: '#ec4899' },
  { id: 'backing_vocals', label: 'Backing Vocals', shortLabel: 'BACK VOX', iconName: 'Mic2', defaultColor: '#f43f5e' },
  { id: 'sound_tech', label: 'Sound Engineer / Tech', shortLabel: 'FOH TECH', iconName: 'Sliders', defaultColor: '#10b981' },
];

export const SECTION_COLORS: Record<string, string> = {
  intro: '#3b82f6', // blue
  verse: '#10b981', // green
  chorus: '#ef4444', // red/coral
  bridge: '#8b5cf6', // purple
  solo: '#f59e0b', // amber
  breakdown: '#06b6d4', // cyan
  outro: '#64748b', // slate
  vamp: '#ec4899', // pink
  count_in: '#eab308',
};

export const DEFAULT_AUDIO_CONFIG: AudioMixConfig = {
  clickEnabled: true,
  clickVolume: 0.85,
  clickSubdivision: '1/4',
  downbeatFreq: 1600,
  offbeatFreq: 1000,
  clickPan: 0.0, // Center (or Pan left -1.0 for IEM split)
  vocalCuesEnabled: true,
  vocalCuesVolume: 0.9,
  voiceLeadInBars: 2,
  speechPitch: 1.05,
  speechRate: 1.15,
  countInEnabled: true,
  countInBars: 1,
  masterVolume: 0.95,
};

export const DEFAULT_MIDI_MAPPINGS: MidiMapping[] = [
  { id: 'map_1', action: 'PLAY_PAUSE', label: 'Pedal 1 (Start/Pause)', type: 'note', channel: 0, number: 60 },
  { id: 'map_2', action: 'NEXT_SONG', label: 'Pedal 2 (Next Song)', type: 'note', channel: 0, number: 62 },
  { id: 'map_3', action: 'PREV_SONG', label: 'Pedal 3 (Prev Song)', type: 'note', channel: 0, number: 59 },
  { id: 'map_4', action: 'NEXT_SECTION', label: 'Pedal 4 (Next Section)', type: 'note', channel: 0, number: 64 },
  { id: 'map_5', action: 'TRIGGER_EMERGENCY_REPEAT', label: 'Pedal 5 (Repeat Chorus)', type: 'cc', channel: 0, number: 64 },
  { id: 'map_6', action: 'TAP_TEMPO', label: 'Pedal 6 (Tap Tempo)', type: 'note', channel: 0, number: 65 },
];

export const EMERGENCY_CUES: { type: EmergencyCueType; label: string; voicePrompt: string; color: string; description: string }[] = [
  { type: 'REPEAT_CHORUS', label: 'REPEAT CHORUS', voicePrompt: 'Repeat chorus, repeat chorus!', color: '#ef4444', description: 'Loop current chorus for crowd singalong' },
  { type: 'EXTEND_SOLO', label: 'EXTEND SOLO (x2)', voicePrompt: 'Extend solo, keep rocking!', color: '#f59e0b', description: 'Give soloist another 8 bars' },
  { type: 'END_ON_1', label: 'END ON 1', voicePrompt: 'Watch master! Ending hard on one!', color: '#dc2626', description: 'Hit the downbeat and cut clean' },
  { type: 'CUT_SONG', label: 'CUT SONG NOW', voicePrompt: 'Cut track, cut track now!', color: '#b91c1c', description: 'Immediate clean mute / stop' },
  { type: 'SKIP_OUTRO', label: 'SKIP TO OUTRO', voicePrompt: 'Skip to outro on next bar!', color: '#8b5cf6', description: 'Bypass bridge and go straight to ending' },
  { type: 'VAMP_HOLD', label: 'VAMP / HOLD CHORD', voicePrompt: 'Hold chord, vamp till cue!', color: '#06b6d4', description: 'Hold current progression for stage banter' },
  { type: 'KEY_CHANGE', label: 'MODULATE +1 STEP', voicePrompt: 'Key change up one half step!', color: '#ec4899', description: 'Modulate for high energy final chorus' },
];

export const SAMPLE_SONGS: Song[] = [
  {
    id: 'song_1',
    title: 'Midnight Neon Run',
    artist: 'BandSync Originals',
    bpm: 128,
    timeSignature: '4/4',
    key: 'E Minor',
    leadInBars: 1,
    bufferSecondsAfter: 20,
    createdAt: Date.now() - 3600000 * 24 * 7,
    updatedAt: Date.now() - 3600000 * 2,
    tags: ['High Energy', 'Opener', 'Synthwave Rock'],
    sections: [
      {
        id: 'sec_1',
        name: 'Intro (Synth & Hi-Hat)',
        type: 'intro',
        bars: 8,
        timeSignature: '4/4',
        color: '#3b82f6',
        chords: 'Em | C | G | D',
        lyrics: '(Atmospheric synth swell + straight 16th hats)',
        roleNotes: {
          drums: 'Straight 16th hats on beat 1. Snare build on bar 7-8.',
          bass: 'Tacet first 4 bars, enter on Bar 5 driving 8th notes on E.',
          lead_guitar: 'Staccato arpeggio with 1/8d stereo delay. Volume pedal swell.',
          rhythm_guitar: 'Tacet until bar 5. Chunky palm-muted power chords.',
          keys: 'Preset #14: Blade Runner Pad + Arp 16ths in Em.',
          lead_vocals: 'Get crowd hyped. Check wireless mic.',
          backing_vocals: 'Tacet.',
          sound_tech: 'Reverb send on synth bus + punch kick in subs.',
        },
        midiTrigger: { enabled: true, channel: 1, programChange: 14, description: 'Synth Preset 14' },
      },
      {
        id: 'sec_2',
        name: 'Verse 1',
        type: 'verse',
        bars: 16,
        timeSignature: '4/4',
        color: '#10b981',
        chords: 'Em | C | Am | B7 (x2)',
        lyrics: 'City lights reflection on the glass / Counting every second as they pass / Running through the shadows of the street / Syncing every heartbeat to the beat',
        roleNotes: {
          drums: 'Four on the floor kick, dry snare on 2 and 4, tight hats.',
          bass: 'Syncopated groove with root-octave pops. Watch the B7 turnaround on bar 8 and 16.',
          lead_guitar: 'Clean Strat with chorus, ambient fills behind vocals.',
          rhythm_guitar: 'Crisp funk skank on beats 2 & 4.',
          keys: 'Electric Piano Rhodes with subtle phaser.',
          lead_vocals: 'Smooth chest voice, build dynamic intensity on second half.',
          backing_vocals: 'Harmonies on bar 9-16 ("Ahhh / To the beat").',
          sound_tech: 'Vocals front and centered, light slapback delay.',
        },
        midiTrigger: { enabled: true, channel: 2, programChange: 3, description: 'Guitar Clean + Chorus' },
      },
      {
        id: 'sec_3',
        name: 'Pre-Chorus (Build)',
        type: 'breakdown',
        bars: 8,
        timeSignature: '4/4',
        color: '#06b6d4',
        chords: 'C | D | Em | G | C | D | Bsus4 | B7',
        lyrics: 'And we rise above the noise / Every shadow finds a voice / Feel the current start to surge!',
        roleNotes: {
          drums: 'Tom groove with crescendo. Full crash wash on bar 8 beat 4.',
          bass: 'Driving crescendos, slide up to high E octave on bar 7.',
          lead_guitar: 'Feedback swell + octave melody running up the neck.',
          rhythm_guitar: 'Open barre chords building volume.',
          keys: 'Dual saw lead rising filter cutoff.',
          lead_vocals: 'Belt with rasp on "start to surge!"',
          backing_vocals: 'High third & fifth harmonies on "voice" and "surge".',
          sound_tech: 'Open FOH sub master, engage vocal hall reverb on bar 8.',
        },
      },
      {
        id: 'sec_4',
        name: 'Chorus 1 (Drop)',
        type: 'chorus',
        bars: 16,
        timeSignature: '4/4',
        color: '#ef4444',
        chords: 'Em | G | C | D (x4)',
        lyrics: 'WE ARE THE PULSE OF THE NIGHT! / IGNITING FIRE IN THE SKY! / HOLD ON TIGHT AND NEVER LET GO! / THIS IS THE FREEDOM WE KNOW!',
        roleNotes: {
          drums: 'MASSIVE half-time rock beat on bar 1-8, then double-time driving 8s bar 9-16.',
          bass: 'Fuzz pedal ON (Big Muff). Thick low-end wall of sound.',
          lead_guitar: 'High-gain rhythm doublestops with wah wide open.',
          rhythm_guitar: 'Full Marshall crunch power chords.',
          keys: 'SuperSaw Brass chords + Moog bass reinforcement.',
          lead_vocals: 'Full power high G4 belt! Jump and engage crowd.',
          backing_vocals: 'Full 3-part gang vocals on all chorus lines.',
          sound_tech: 'Vocal compressor active, full stereo guitar spread.',
        },
        midiTrigger: { enabled: true, channel: 2, programChange: 8, description: 'Guitar High Gain Crunch' },
      },
      {
        id: 'sec_5',
        name: 'Guitar Solo',
        type: 'solo',
        bars: 16,
        timeSignature: '4/4',
        color: '#f59e0b',
        chords: 'Em | D | C | B7 | Em | D | Am | B7',
        lyrics: '[GUITAR HERO MOMENT - Center Stage]',
        roleNotes: {
          drums: 'Heavy driving beat, accent guitar rhythmic unison bursts.',
          bass: 'Walking rock bassline with overdrive.',
          lead_guitar: 'LEAD SOLO: Tube Screamer + Tape Echo. Step to center monitor!',
          rhythm_guitar: 'Tight rhythmic backing. Keep time solid.',
          keys: 'Organ Leslie rotating fast + B3 drawbars 888000000.',
          lead_vocals: 'Encourage crowd cheers for guitarist.',
          backing_vocals: 'Tacet.',
          sound_tech: 'Solo boost +3dB on Lead Guitar channel.',
        },
        midiTrigger: { enabled: true, channel: 2, programChange: 22, description: 'Lead Boost + Echo' },
      },
      {
        id: 'sec_6',
        name: 'Outro & Big Ending',
        type: 'outro',
        bars: 8,
        timeSignature: '4/4',
        color: '#64748b',
        chords: 'Em | C | D | Em (Hold on 1)',
        lyrics: 'Hold on tight... We are the pulse! [FINAL HIT ON 1]',
        roleNotes: {
          drums: 'Fast triplets roll into big crash hit on Beat 1. Cymbal swell to decay.',
          bass: 'Low E fundamental bomb. Let ring until cutoff signal.',
          lead_guitar: 'Whammy dive bomb into feedback.',
          rhythm_guitar: 'Final Em chord hit on Beat 1, let resonate.',
          keys: 'Sub rumble + cutoff filter closing.',
          lead_vocals: '"THANK YOU LONDON!" Final scream on 1.',
          backing_vocals: 'Final unison hit on "Pulse!"',
          sound_tech: 'Long echo tail on vocal mic into black.',
        },
      },
    ],
  },
  {
    id: 'song_2',
    title: 'Echoes of the Skyline',
    artist: 'BandSync Originals',
    bpm: 96,
    timeSignature: '4/4',
    key: 'A Major',
    leadInBars: 1,
    bufferSecondsAfter: 15,
    createdAt: Date.now() - 3600000 * 24 * 5,
    updatedAt: Date.now() - 3600000 * 4,
    tags: ['Anthem', 'Mid-Tempo', 'Harmonies'],
    sections: [
      {
        id: 's2_1',
        name: 'Intro (Acoustic & Piano)',
        type: 'intro',
        bars: 4,
        timeSignature: '4/4',
        color: '#3b82f6',
        chords: 'A | F#m | D | E',
        roleNotes: {
          drums: 'Tacet first 2 bars, soft cross-stick and warm shaker bar 3-4.',
          bass: 'Deep warm round bass on roots.',
          lead_guitar: 'Acoustic guitar fingerpicking.',
          rhythm_guitar: 'Tacet.',
          keys: 'Grand Piano gentle ballad voicings.',
          lead_vocals: 'Intimate vocal tone.',
          backing_vocals: 'Tacet.',
          sound_tech: 'Warm acoustic space, gentle compression.',
        },
      },
      {
        id: 's2_2',
        name: 'Verse 1',
        type: 'verse',
        bars: 16,
        timeSignature: '4/4',
        color: '#10b981',
        chords: 'A | C#m | F#m | D (x2)',
        lyrics: 'Standing on the edge of daylight / Watching morning paint the towers gold / Every memory we held tight / Is a story waiting to be told',
        roleNotes: {
          drums: 'Rim click groove, brushed ride cymbal.',
          bass: 'Melodic supportive lines in lower register.',
          lead_guitar: 'Volume swells with shimmering shimmer reverb.',
          rhythm_guitar: 'Acoustic full chords.',
          keys: 'Piano left-hand arpeggios + warm string pad layer.',
          lead_vocals: 'Tender storytelling delivery.',
          backing_vocals: 'Soft harmonies on line 3 and 4.',
          sound_tech: 'Pristine vocal clarity.',
        },
      },
      {
        id: 's2_3',
        name: 'Chorus (Anthemic)',
        type: 'chorus',
        bars: 16,
        timeSignature: '4/4',
        color: '#ef4444',
        chords: 'D | E | A E/G# | F#m | D | E | A | A',
        lyrics: 'ECHOES OF THE SKYLINE RINGING CLEAR / LIFTING US BEYOND THE SHADOWS OF FEAR / TOGETHER WE WILL SHINE!',
        roleNotes: {
          drums: 'Open hi-hat rock ballad groove with heavy kick.',
          bass: 'Full sustained low notes, drive the descending E/G# walkdown.',
          lead_guitar: 'U2 style dotted-8th delayed arpeggios.',
          rhythm_guitar: 'Open electric overdrive chords.',
          keys: 'Full octave piano + soaring string ensemble.',
          lead_vocals: 'Big expressive soaring vocals.',
          backing_vocals: 'Full harmony choir blend.',
          sound_tech: 'Wide stereo image, deep plate reverb.',
        },
      },
    ],
  },
  {
    id: 'song_3',
    title: 'Rhythm & Thunder (6/8)',
    artist: 'BandSync Originals',
    bpm: 174,
    timeSignature: '6/8',
    key: 'D Minor',
    leadInBars: 1,
    bufferSecondsAfter: 25,
    createdAt: Date.now() - 3600000 * 24 * 3,
    updatedAt: Date.now() - 3600000 * 1,
    tags: ['6/8 Ballad', 'Heavy Blues Rock', 'Epic'],
    sections: [
      {
        id: 's3_1',
        name: 'Intro 6/8 Shuffle',
        type: 'intro',
        bars: 8,
        timeSignature: '6/8',
        color: '#3b82f6',
        chords: 'Dm | Bb | Gm | A7',
        roleNotes: {
          drums: '6/8 Blues rock shuffle with ghost notes on snare.',
          bass: 'Rolling triplets in D minor.',
          lead_guitar: 'Bluesy doublestop intro riffs.',
          rhythm_guitar: 'Clean crunch 6/8 chord stabs on beats 1 and 4.',
          keys: 'Hammond B3 with warm rotary overdrive.',
          lead_vocals: 'Feel the 6/8 sway.',
          backing_vocals: 'Tacet.',
          sound_tech: 'Snare body punch, warm low-mids on bass.',
        },
      },
      {
        id: 's3_2',
        name: 'Verse 1',
        type: 'verse',
        bars: 12,
        timeSignature: '6/8',
        color: '#10b981',
        chords: 'Dm | C | Bb | A7 (x2)',
        lyrics: 'Rain drops falling on the asphalt / Thunder rumbling in the distance / No excuses, nobody to fault / Breaking free with fierce resistance',
        roleNotes: {
          drums: 'Dynamic ride groove, building intensity on bar 9-12.',
          bass: 'Pumping root-fifth-octave 6/8 lines.',
          lead_guitar: 'Soulful minor pentatonic blues fills.',
          rhythm_guitar: 'Chunky power chords.',
          keys: 'Organ swells with Leslie speed switch on bar 11.',
          lead_vocals: 'Gritty soul vocals.',
          backing_vocals: 'Gospel style vocal backing on bar 7-12.',
          sound_tech: 'Parallel compression on drum bus.',
        },
      },
      {
        id: 's3_3',
        name: 'Chorus (Thunder Roar)',
        type: 'chorus',
        bars: 16,
        timeSignature: '6/8',
        color: '#ef4444',
        chords: 'Bb | C | Dm | Dm | Bb | C | A7 | A7',
        lyrics: 'HEAR THE THUNDER SHAKE THE GROUND! / WE ARE LOST AND WE ARE FOUND! / LIGHTNING IN OUR VEINS!',
        roleNotes: {
          drums: 'Heavy tribal toms mixed with driving crash cymbals.',
          bass: 'Distorted drop-D low end punch.',
          lead_guitar: 'Harmonized twin guitar lead lines.',
          rhythm_guitar: 'Full open-voiced barre chords.',
          keys: 'Heavy distorted synth bass layer underneath.',
          lead_vocals: 'Maximum energy rock belt!',
          backing_vocals: 'Anthem harmonies on "SHAKE THE GROUND!"',
          sound_tech: 'Full stadium soundscape.',
        },
      },
    ],
  },
  {
    id: 'song_4',
    title: 'Supernova Encores',
    artist: 'BandSync Originals',
    bpm: 140,
    timeSignature: '4/4',
    key: 'F# Minor',
    leadInBars: 1,
    bufferSecondsAfter: 30,
    createdAt: Date.now() - 3600000 * 24 * 2,
    updatedAt: Date.now() - 3600000 * 1,
    tags: ['Encore', 'Crowd Pleaser', 'Fast'],
    sections: [
      {
        id: 's4_1',
        name: 'Crowd Clap & Count-In',
        type: 'intro',
        bars: 8,
        timeSignature: '4/4',
        color: '#3b82f6',
        chords: 'F#m (Pedal)',
        roleNotes: {
          drums: 'Floor tom pulse on quarter notes. Get the crowd clapping above head.',
          bass: 'Punchy low F# synth bass.',
          lead_guitar: 'Pick scrapes and delay oscillation.',
          rhythm_guitar: 'Muted rhythmic chugs.',
          keys: 'Arpeggiator running in 16ths.',
          lead_vocals: '"LETS GO EVERYBODY! 1, 2, 1 2 3 4!"',
          backing_vocals: 'Clapping along on 2 & 4.',
          sound_tech: 'Mute crowd mics, open main PA.',
        },
      },
      {
        id: 's4_2',
        name: 'Main Explosive Chorus',
        type: 'chorus',
        bars: 16,
        timeSignature: '4/4',
        color: '#ef4444',
        chords: 'F#m | D | A | E (x4)',
        lyrics: 'EXPLODING LIKE A SUPERNOVA! / THE NIGHT HAS ONLY JUST BEGUN! / WE ARE THE CHOSEN ONES!',
        roleNotes: {
          drums: 'Fast punk-rock driving beat with double time snare.',
          bass: 'Eighth notes non-stop with pick attack.',
          lead_guitar: 'Octave chords and melodic hooks.',
          rhythm_guitar: 'Full throttle high-energy rhythm.',
          keys: 'Bright euro-synth stabs.',
          lead_vocals: 'Huge stage presence, jumping and commanding the room.',
          backing_vocals: 'High harmony vocal shouts.',
          sound_tech: 'Stage lights sync trigger, master limiter at -0.1dB.',
        },
      },
    ],
  },
];

export const SAMPLE_SETLIST: Setlist = {
  id: 'setlist_main',
  name: 'Summer Festival Live 2026 - Main Stage',
  date: '2026-08-20',
  venueName: 'The Electric Grand Arena',
  targetStartTime: '21:00',
  targetCurfewTime: '22:15',
  interSongBufferSec: 25,
  updatedAt: Date.now(),
  notes: 'Headlining 75-min slot. STRICT 22:15 Curfew (€500/min fine for overrun). Keep banter concise.',
  items: [
    { songId: 'song_1', customNotes: 'Energetic opener, singer checks crowd' },
    { songId: 'song_2', customNotes: 'Guitarist switches to Acoustic (15s buffer)' },
    { songId: 'song_3', customNotes: 'Bass switches to Drop-D tuning' },
    { songId: 'song_4', customNotes: 'Encore! Bring everyone on stage for the final hit' },
  ],
};

export const ALL_DEFAULT_SONGS: Song[] = [...HOTT_SHOTS_SONGS, ...SAMPLE_SONGS];

export const DEFAULT_SETLISTS: Setlist[] = [
  HOTT_SHOTS_AUGUST_SETLIST,
  SAMPLE_SETLIST,
];

export const SAMPLE_GIGS: GigEvent[] = [
  {
    id: 'gig_1',
    title: 'Electric Summer Stage Festival',
    venueName: 'The Electric Grand Arena',
    address: '142 Kingsland Road, London E2 8DY',
    city: 'London',
    date: '2026-08-20',
    loadInTime: '15:30',
    soundcheckTime: '17:00',
    doorsTime: '19:30',
    stageTime: '21:00',
    curfewTime: '22:15',
    performanceFee: 2800,
    currency: '£',
    setlistId: 'setlist_main',
    status: 'confirmed',
    contactPerson: 'Dave Miller (Stage Manager)',
    contactPhone: '+44 7700 900451',
    bandAvailability: {
      m_1: 'available',
      m_2: 'available',
      m_3: 'available',
      m_4: 'available',
      m_5: 'available',
      m_6: 'available',
    },
    notes: 'In-Ear Monitor splits provided from Stage Box A. Wi-Fi PA SSID: "VENUE_PA_5G" (Pass: soundcheck2026). Parking behind backstage gate 3.',
  },
  {
    id: 'gig_2',
    title: 'Waterfront Summer Beats',
    venueName: 'The Waterfront Pier Stage',
    address: 'Pier 7, Brighton Marina',
    city: 'Brighton',
    date: '2026-09-05',
    loadInTime: '16:00',
    soundcheckTime: '18:00',
    doorsTime: '19:00',
    stageTime: '20:30',
    curfewTime: '23:00',
    performanceFee: 1950,
    currency: '£',
    setlistId: 'setlist_main',
    status: 'confirmed',
    contactPerson: 'Sarah Jenkins (Promoter)',
    contactPhone: '+44 7700 900892',
    bandAvailability: {
      m_1: 'available',
      m_2: 'available',
      m_3: 'tentative',
      m_4: 'available',
      m_5: 'available',
      m_6: 'available',
    },
    notes: 'Outdoor stage under marquee. Sea breeze dampness protection for tube amps.',
  },
  {
    id: 'gig_3',
    title: 'The Rock Foundry Headline Night',
    venueName: 'The Foundry Club',
    address: '88 Canal St, Manchester M1 3WD',
    city: 'Manchester',
    date: '2026-09-18',
    loadInTime: '17:00',
    soundcheckTime: '18:30',
    doorsTime: '20:00',
    stageTime: '21:30',
    curfewTime: '23:30',
    performanceFee: 1500,
    currency: '£',
    setlistId: 'setlist_main',
    status: 'in_discussion',
    contactPerson: 'Alex Vance',
    contactPhone: '+44 7700 900123',
    bandAvailability: {
      m_1: 'available',
      m_2: 'available',
      m_3: 'available',
      m_4: 'available',
      m_5: 'available',
    },
    notes: 'Full 5-piece Hot Shots lineup confirmed.',
  },
];

export const SAMPLE_STAGE_RIDER: StageRider = {
  id: 'rider_1',
  title: 'Hot Shots - 5-Piece Stage Rider & Tech Input List',
  bandName: 'HOT SHOTS',
  contactName: 'Mart (Band Leader & Bass)',
  contactPhone: '+44 7700 900111',
  contactEmail: 'tech@hotshots.live',
  stagePlotItems: [
    { id: 'sp_1', type: 'drums', label: 'Drums (Sporty)', x: 50, y: 20, rotation: 0, powerRequired: true },
    { id: 'sp_2', type: 'bass_amp', label: 'Bass Rig (Mart - SVT + XLR DI)', x: 22, y: 28, rotation: 0, channelNumber: 8, powerRequired: true },
    { id: 'sp_3', type: 'guitar_amp', label: 'Lead Guitar (Dan - Kemper Profiler)', x: 78, y: 28, rotation: 0, channelNumber: 10, powerRequired: true },
    { id: 'sp_4', type: 'keyboard', label: 'Keys Station (Tom - Nord + Roland)', x: 16, y: 60, rotation: 15, channelNumber: 12, powerRequired: true },
    { id: 'sp_5', type: 'vocal_mic', label: 'Lead Vox (Rosie - Wireless Shure)', x: 50, y: 80, rotation: 0, channelNumber: 1 },
    { id: 'sp_6', type: 'vocal_mic', label: 'Backing Vox (Dan - Guitar)', x: 80, y: 72, rotation: -15, channelNumber: 2 },
    { id: 'sp_7', type: 'vocal_mic', label: 'Backing Vox (Tom - Keys)', x: 20, y: 72, rotation: 15, channelNumber: 3 },
    { id: 'sp_8', type: 'monitor_wedge', label: 'Wedge Monitor 1 (Rosie)', x: 50, y: 92, rotation: 180 },
    { id: 'sp_9', type: 'monitor_wedge', label: 'Wedge Monitor 2 (Dan)', x: 80, y: 88, rotation: 180 },
    { id: 'sp_10', type: 'monitor_wedge', label: 'Wedge Monitor 3 (Mart / Tom)', x: 20, y: 88, rotation: 180 },
    { id: 'sp_11', type: 'power_drop', label: '4-Way 230V AC Power (Drums - Sporty)', x: 42, y: 15, rotation: 0 },
    { id: 'sp_12', type: 'power_drop', label: '4-Way 230V AC Power (Keys - Tom)', x: 12, y: 55, rotation: 0 },
    { id: 'sp_13', type: 'power_drop', label: '4-Way 230V AC Power (Stage Front / Mart / Rosie / Dan)', x: 50, y: 72, rotation: 0 },
  ],
  inputChannels: [
    { channelNumber: 1, instrument: 'Lead Vocals', performer: 'Rosie', micOrDI: 'Wireless Shure QLX-D (Band Provided)', standType: 'Straight', phantom48v: false, notes: 'Main vocal, reverb & tape delay on FX send' },
    { channelNumber: 2, instrument: 'Backing Vox (Guitar)', performer: 'Dan', micOrDI: 'Shure SM58 / Beta 58A', standType: 'Tall Boom', phantom48v: false, notes: 'High harmonies' },
    { channelNumber: 3, instrument: 'Backing Vox (Keys)', performer: 'Tom', micOrDI: 'Shure SM58', standType: 'Tall Boom', phantom48v: false, notes: 'Mid harmonies' },
    { channelNumber: 4, instrument: 'Kick Drum (In)', performer: 'Sporty', micOrDI: 'Shure Beta 91A', standType: 'None', phantom48v: true, notes: 'Boundary mic inside kick' },
    { channelNumber: 5, instrument: 'Kick Drum (Out)', performer: 'Sporty', micOrDI: 'Audix D6 / AKG D112', standType: 'Short Boom', phantom48v: false, notes: 'Port hole punch' },
    { channelNumber: 6, instrument: 'Snare Top', performer: 'Sporty', micOrDI: 'Shure SM57', standType: 'Clip-on', phantom48v: false, notes: 'Snare crack' },
    { channelNumber: 7, instrument: 'Hi-Hat', performer: 'Sporty', micOrDI: 'AKG C451 / Rode NT5', standType: 'Tall Boom', phantom48v: true, notes: 'Tight top end' },
    { channelNumber: 8, instrument: 'Bass DI (Clean/Pre)', performer: 'Mart', micOrDI: 'Radial J48 Active DI', standType: 'None', phantom48v: true, notes: 'Clean sub fundamental' },
    { channelNumber: 9, instrument: 'Bass Mic / Amp', performer: 'Mart', micOrDI: 'Sennheiser e906 / MD421', standType: 'Short Boom', phantom48v: false, notes: 'Overdrive tone' },
    { channelNumber: 10, instrument: 'Lead Guitar (L)', performer: 'Dan', micOrDI: 'XLR Out from Kemper', standType: 'None', phantom48v: false, notes: 'Stereo profile Left' },
    { channelNumber: 11, instrument: 'Lead Guitar (R)', performer: 'Dan', micOrDI: 'XLR Out from Kemper', standType: 'None', phantom48v: false, notes: 'Stereo profile Right' },
    { channelNumber: 12, instrument: 'Keyboards (L)', performer: 'Tom', micOrDI: 'Radial ProD2 (Stereo)', standType: 'None', phantom48v: false, notes: 'Synths & Piano Left' },
    { channelNumber: 13, instrument: 'Keyboards (R)', performer: 'Tom', micOrDI: 'Radial ProD2 (Stereo)', standType: 'None', phantom48v: false, notes: 'Synths & Piano Right' },
    { channelNumber: 14, instrument: 'BandSync Click & Cue (IEM only)', performer: 'Mart (Stage Master)', micOrDI: 'Radial StageBug DI', standType: 'None', phantom48v: false, notes: 'CRITICAL: DO NOT ROUTE TO FOH! IEMs ONLY!' },
  ],
  monitorMixes: [
    { mixNumber: 1, assignedTo: 'Lead Vocals (Rosie)', notes: 'In-Ear Monitor Stereo (Mix 1-2): 50% Lead Vox, 25% Keys, 15% Click/Cues, 10% Guitar' },
    { mixNumber: 2, assignedTo: 'Drums (Sporty)', notes: 'In-Ear Monitor Stereo (Mix 3-4): 40% Click Track, 30% Bass DI (Mart), 20% Vox, 10% Guitars' },
    { mixNumber: 3, assignedTo: 'Bass (Mart - Stage Master)', notes: 'Wedge / IEM Mix 5: Bass, Kick, Snare, Rosie Vox, Click/Cues' },
    { mixNumber: 4, assignedTo: 'Lead Guitar (Dan)', notes: 'In-Ear Monitor Stereo (Mix 6-7): Lead Guitar, Click/Cues, Rosie Vox' },
    { mixNumber: 5, assignedTo: 'Keys & Synths (Tom)', notes: 'Wedge / IEM Mix 8: Keys, Backing Vox, Click/Cues, Rosie Vox' },
  ],
  generalRequirements: 'Hot Shots provides wireless transmitters, IEM receivers, and BandSync Stage Master system. Venue to provide 14 mic cables, 6 DI boxes, AC power drops on stage as marked in plot, and competent FOH sound engineer.',
};

export const SAMPLE_BAND_PROFILE: BandProfile = {
  id: 'band_1',
  name: 'HOT SHOTS',
  genre: 'High-Energy Festival, Pop & Rock Party Band',
  accentColor: '#f97316',
  stageTheme: 'stage_dark',
  members: [
    { id: 'm_1', name: 'Mart (You)', role: 'bass', avatar: '⚡', color: '#06b6d4', isMaster: true, phone: '+44 7700 900111', latencyMs: 1.2 },
    { id: 'm_2', name: 'Rosie', role: 'lead_vocals', avatar: '🎤', color: '#ec4899', isMaster: false, phone: '+44 7700 900222', latencyMs: 2.1 },
    { id: 'm_3', name: 'Dan', role: 'lead_guitar', avatar: '🎸', color: '#eab308', isMaster: false, phone: '+44 7700 900333', latencyMs: 3.4 },
    { id: 'm_4', name: 'Tom', role: 'keys', avatar: '🎹', color: '#a855f7', isMaster: false, phone: '+44 7700 900555', latencyMs: 2.7 },
    { id: 'm_5', name: 'Sporty', role: 'drums', avatar: '🥁', color: '#f97316', isMaster: false, phone: '+44 7700 900444', latencyMs: 1.8 },
  ],
};
